// src/lib/components/Navigation.svelte
<script lang="ts">
	import { AppBar } from '@skeletonlabs/skeleton';

	import Theater from 'svelte-material-icons/Theater.svelte';
	import DevTo from 'svelte-material-icons/DevTo.svelte';
	import FolderMusic from 'svelte-material-icons/FolderMusic.svelte';
	import GamepadVariant from 'svelte-material-icons/GamepadVariant.svelte';

	export let isAuthenticated: boolean = false;

	function loginClicked() {}

	function logoutClicked() {}
</script>

<AppBar app dense>
	<svelte:fragment slot="lead">
		<a href="/" class="btn">
			<img
				class="h-10"
				src="assets/white_logo_transparent_background.png"
				alt="kungraseri productions logo"
			/>
		</a>
	</svelte:fragment>
	<div>
		<a href="/projects" class="btn">
			<span class="mr-2">projects</span>
			<DevTo />
		</a>
		<a href="/music" class="btn">
			<span class="mr-2">music</span>
			<FolderMusic />
		</a>
	</div>
	<svelte:fragment slot="trail">
		<div class="row wrap justify-end">
			{#if isAuthenticated}
				<a href="/" class="btn-sm">Logout</a>
			{:else}
				<a href="/" class="btn-sm">Login / Register</a>
			{/if}
		</div>
	</svelte:fragment>
</AppBar>

// src/components/Navigation.vue
<template>
  <v-app-bar app dense>
    <v-toolbar-title>
      <a href="/">
        <v-img contain max-height="75" width="250" :src="logoPath"></v-img>
      </a>
    </v-toolbar-title>
    <v-btn text to="stream" large>
      <span class="mr-2">stream</span>
      <v-icon>mdi-theater</v-icon>
    </v-btn>
    <v-btn text to="projects" large>
      <span class="mr-2">projects</span>
      <v-icon>mdi-dev-to</v-icon>
    </v-btn>
    <v-btn text to="music" large>
      <span class="mr-2">music</span>
      <v-icon>mdi-folder-music</v-icon>
    </v-btn>
    <v-divider vertical class="mx-3"></v-divider>
    <v-spacer></v-spacer>
    <v-layout row wrap justify-end>
      <v-divider vertical class="mx-3"></v-divider>
      <v-flex xs2>
        <v-btn
          text
          large
          v-if="!isAuthenticated"
          color="primary"
          @click="loginClicked"
          >Login / Register</v-btn
        >
        <v-btn
          text
          large
          color="secondary"
          v-else-if="isAuthenticated"
          @click="logoutClicked"
          >Logout</v-btn
        >
      </v-flex>
    </v-layout>
  </v-app-bar>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

@Component({})
export default class NavigationComponent extends Vue {
  @Prop({ type: Boolean, default: false })
  public isAuthenticated: boolean = false;

  private logoPath = require("../assets/white_logo_transparent_background.png");

  public loginClicked() {
    this.$emit("loginClicked");
  }
  public logoutClicked() {
    this.$emit("logoutClicked");
  }
}
</script>
